# Geant4 Macro file for batch mode

#/process/em/verbose 0
/analysis/verbose 1
/run/verbose 0
/run/initialize


/gun/particle mu-
/gun/energy 3 GeV
#/gun/position  0 20 0 mm
#/gun/position  6.616 0 0 mm
/gun/position  250 0 0 mm
#/gun/position  0 0 124.80 cm
#/gun/direction 0 -1 0    #90deg
/gun/direction -1 0 0    #0 deg
#/gun/direction -2 2 1    #0 deg
#/gun/direction 0 -1 -1    #45deg
#/gun/direction 0 -1 -1.73  #30deg
#/gun/direction 0 -1 -0.577 #60deg
#/gun/direction 0 0 1
/run/beamOn 100
#/run/beamOn 1000
