# Geant4 Macro file for batch mode

#/process/em/verbose 0
/analysis/verbose 1
/run/verbose 0
/run/initialize


#/gun/particle mu-
/gun/particle e-
/gun/energy 5 GeV

#/gun/particle opticalphoton
#/gun/energy 3.5 eV


#/gun/position  0 -0.05 -15 cm
/gun/position 0 5 -400. cm
#/gun/position  0 0 -18 cm
#/gun/direction 0 -1 0    #90deg
/gun/direction 0 -1 0    #0 deg
#/gun/direction 0 -1 -1    #45deg
#/gun/direction 0 -1 -1.73  #30deg
#/gun/direction 0 -1 -0.577 #60deg
#/gun/direction 0 0 1
/run/beamOn 1
